-- Seed data for footfits.pk

-- Insert sample sliders
INSERT INTO sliders (title, subtitle, cta_text, cta_link, background_color, image_url, sort_order, is_active) VALUES
('Authentic Branded Shoes', 'Pre-loved & Brand New from USA/Europe', 'Shop Now', '/shop', '#284E3D', '/placeholder-slider-1.jpg', 1, true),
('Thrift Prices, Premium Quality', 'Save up to 70% on authentic footwear', 'Browse Collection', '/shop', '#284E3D', '/placeholder-slider-2.jpg', 2, true),
('New Arrivals Weekly', 'Fresh stock of Nike, Adidas, New Balance & more', 'See What''s New', '/shop?sort=newest', '#284E3D', '/placeholder-slider-3.jpg', 3, true);

-- Insert sample products
INSERT INTO products (slug, name, brand, gender, category, condition_label, condition_score, sizes, price, original_price, color, description, condition_notes, images, is_new, is_sale, status) VALUES
('nike-air-max-90', 'Air Max 90', 'Nike', 'Men', 'Sneakers', 'Excellent 9/10', 9, '[8, 9, 10, 11]', 6500, 9000, 'White/Red', 'Classic Nike Air Max 90 in excellent condition. Minimal wear, clean uppers, and fully functional air unit.', 'Minor creasing on toe box, no major flaws. Comes with original box.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg", "/placeholder-shoe-3.jpg"]', false, true, 'active'),
('adidas-ultraboost-22', 'Ultraboost 22', 'Adidas', 'Men', 'Running', 'Excellent 9/10', 9, '[9, 10, 11, 12]', 8900, 14000, 'Black/White', 'Adidas Ultraboost 22 with responsive Boost cushioning. Barely worn, like-new condition.', 'Excellent condition, minimal sole wear. Original insoles included.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('new-balance-990v5', '990v5', 'New Balance', 'Men', 'Lifestyle', 'Very Good 8/10', 8, '[8, 9, 10, 11, 12]', 8500, 15000, 'Grey', 'New Balance 990v5 - Made in USA. Premium suede and mesh construction.', 'Light wear on outsole, uppers in great shape. No box included.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg", "/placeholder-shoe-3.jpg"]', false, true, 'active'),
('nike-dunk-low-panda', 'Dunk Low Panda', 'Nike', 'Unisex', 'Sneakers', 'Excellent 9/10', 9, '[6, 7, 8, 9, 10, 11]', 5800, 8500, 'Black/White', 'Iconic Nike Dunk Low in the popular Panda colorway. Clean black and white leather.', 'Excellent condition with minimal wear. Original box and laces included.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('asics-gel-kayano-29', 'Gel-Kayano 29', 'ASICS', 'Women', 'Running', 'Good 7/10', 7, '[6, 7, 8, 9]', 4200, 9500, 'Blue/Pink', 'ASICS Gel-Kayano 29 stability running shoe. Great for overpronators.', 'Moderate wear on outsole, uppers still in good condition. Insoles show some compression.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('hoka-bondi-8', 'Bondi 8', 'HOKA', 'Men', 'Running', 'Very Good 8/10', 8, '[9, 10, 11, 12, 13]', 9000, 16000, 'White/Blue', 'HOKA Bondi 8 - Maximum cushioning for long runs. Lightly used.', 'Very good condition, light wear on heel. Plenty of cushioning life left.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg", "/placeholder-shoe-3.jpg"]', false, true, 'active'),
('converse-chuck-taylor-high', 'Chuck Taylor High', 'Converse', 'Unisex', 'Casual', 'Good 7/10', 7, '[6, 7, 8, 9, 10, 11]', 2800, 5000, 'Black', 'Classic Converse Chuck Taylor All Star High Top in black canvas.', 'Good condition with normal wear. Some scuffing on rubber toe cap and sole.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('puma-rs-x-reinvention', 'RS-X Reinvention', 'Puma', 'Kids', 'Sneakers', 'Brand New', 10, '[1, 2, 3, 4, 5]', 4500, 4500, 'Multi-Color', 'Brand new Puma RS-X for kids. Chunky retro design with bold colors.', 'Brand new in box, never worn. All tags attached.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', true, false, 'active'),
('nike-air-force-1-low', 'Air Force 1 Low', 'Nike', 'Women', 'Sneakers', 'Excellent 9/10', 9, '[6, 7, 8, 9, 10]', 5200, 8000, 'White', 'Nike Air Force 1 Low in classic all-white leather. Timeless design.', 'Excellent condition, minimal creasing. Cleaned and ready to wear.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg", "/placeholder-shoe-3.jpg"]', false, true, 'active'),
('vans-old-skool', 'Old Skool', 'Vans', 'Unisex', 'Skate', 'Good 6/10', 6, '[7, 8, 9, 10, 11]', 3000, 5500, 'Black/White', 'Vans Old Skool with iconic side stripe. Classic skate shoe.', 'Good wearable condition. Sole shows wear, uppers have some scuffs but intact.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('hoka-clifton-9', 'Clifton 9', 'HOKA', 'Women', 'Running', 'Very Good 8/10', 8, '[6, 7, 8, 9, 10]', 7500, 13000, 'Pink/White', 'HOKA Clifton 9 - Lightweight cushioned running shoe. Low mileage.', 'Very good condition, light wear on outsole. Upper mesh in excellent shape.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('adidas-superstar', 'Superstar', 'Adidas', 'Unisex', 'Lifestyle', 'Excellent 9/10', 9, '[6, 7, 8, 9, 10, 11, 12]', 4000, 6500, 'White/Black', 'Adidas Superstar with iconic shell toe. Classic 3-stripes design.', 'Excellent condition, minimal wear. Shell toe clean, no major scuffs.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('new-balance-574-classic', '574 Classic', 'New Balance', 'Men', 'Lifestyle', 'Good 7/10', 7, '[8, 9, 10, 11, 12]', 3500, 6000, 'Grey/Navy', 'New Balance 574 in classic grey and navy colorway. Retro running style.', 'Good condition with moderate wear. Suede shows some aging but still presentable.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('nike-air-jordan-1-low', 'Air Jordan 1 Low', 'Nike', 'Men', 'Sneakers', 'Excellent 9/10', 9, '[8, 9, 10, 11, 12]', 7800, 12000, 'Black/Red', 'Air Jordan 1 Low in classic Chicago-inspired colorway. Premium leather.', 'Excellent condition, barely worn. Leather uppers pristine, minimal sole wear.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg", "/placeholder-shoe-3.jpg"]', false, true, 'active'),
('asics-gel-nimbus-25', 'Gel-Nimbus 25', 'ASICS', 'Men', 'Running', 'Brand New', 10, '[9, 10, 11, 12, 13]', 10500, 10500, 'Blue/Orange', 'Brand new ASICS Gel-Nimbus 25. Premium neutral cushioned running shoe.', 'Brand new in box with all tags. Never worn.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', true, false, 'active'),
('puma-suede-classic', 'Suede Classic', 'Puma', 'Women', 'Lifestyle', 'Very Good 8/10', 8, '[6, 7, 8, 9, 10]', 3200, 5000, 'Burgundy', 'Puma Suede Classic in rich burgundy color. Timeless retro design.', 'Very good condition, suede brushed and cleaned. Minor wear on sole.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('new-balance-fresh-foam-1080', 'Fresh Foam 1080', 'New Balance', 'Women', 'Running', 'Excellent 9/10', 9, '[6, 7, 8, 9, 10]', 6800, 11000, 'Purple/White', 'New Balance Fresh Foam 1080 - Plush cushioned running shoe. Low mileage.', 'Excellent condition, minimal wear. Fresh Foam midsole still very responsive.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('nike-pegasus-40', 'Pegasus 40', 'Nike', 'Men', 'Running', 'Very Good 8/10', 8, '[9, 10, 11, 12]', 5500, 9000, 'Black/Volt', 'Nike Pegasus 40 - Versatile daily running shoe. Moderate mileage.', 'Very good condition, moderate outsole wear. Upper mesh intact, no tears.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('adidas-stan-smith', 'Stan Smith', 'Adidas', 'Unisex', 'Lifestyle', 'Good 7/10', 7, '[6, 7, 8, 9, 10, 11]', 3800, 7000, 'White/Green', 'Adidas Stan Smith - Iconic tennis-inspired sneaker with green heel tab.', 'Good condition with normal wear. Some yellowing on midsole, uppers decent.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg"]', false, true, 'active'),
('salomon-speedcross-5', 'Speedcross 5', 'Salomon', 'Men', 'Trail Running', 'Brand New', 10, '[9, 10, 11, 12]', 9500, 9500, 'Black/Red', 'Brand new Salomon Speedcross 5 trail running shoe. Aggressive grip.', 'Brand new in box, never worn. Perfect for trail running and hiking.', '["/placeholder-shoe-1.jpg", "/placeholder-shoe-2.jpg", "/placeholder-shoe-3.jpg"]', true, false, 'active');

-- Insert sample vouchers
INSERT INTO vouchers (code, discount_type, discount_value, min_order_amount, max_uses, used_count, is_active, expires_at) VALUES
('WELCOME10', 'percentage', 10, 3000, 100, 0, true, NOW() + INTERVAL '30 days'),
('FIRST500', 'fixed', 500, 5000, 50, 0, true, NOW() + INTERVAL '30 days'),
('SAVE15', 'percentage', 15, 8000, 0, 0, true, NULL);
